# Generated by Django 5.0.1 on 2024-06-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0004_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='expire_token_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=8000)),
            ],
        ),
    ]
