# Generated by Django 5.0.1 on 2024-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0005_expire_token_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=8000)),
            ],
        ),
    ]
